backend:
  name: git-gateway

local_backend:
  url: http://localhost:8082/api/v1/
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: [ '192.168.0.1' ]

#backend:
#  name: github
#  repo: michaelkargl/portfolio
#  branch: master
#  auth_type: pkce

site_url: https://localhost:9000/portfolio
media_folder: ./static/assets
public_folder: /portfolio/assets

collections:
  - name: curriculum
    title: Curriculum
    label: Curricula
    label_singular: Curriculum
    folder: src/cms/curriculum
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: hellowidget, label: 'Hello Widget', widget: hello-widget, required: false }
      - { name: mywidget, label: 'My Widget', widget: mywidget, required: false }
